### ISSUE TITLE
Add support for international monetary indicators (Euro, Rupee, Ruble, etc.)

### ISSUE THREAD

**Issue by kevinbarabash** [KaTeX/katex-fonts#18]
- [ ] Euro €, https://ctan.org/pkg/eurosym
- [ ] Rupee ₹, https://ctan.org/pkg/tfrupee
- [ ] Ruble ₽, https://tex.stackexchange.com/questions/260722/how-can-i-get-the-russian-ruble-sign suggests using `fontawesome` and `\faRub`

**Comment by kevinbarabash** [comment]
Neither `tfrupee` or `fontawesome` have .mf source files so we'd have to modify our workflow to also work with other font formats as inputs.

**Comment by kevinbarabash** [comment]
I think we should be able to do something similar to:
```
  hookrightarrow => [
    'Generate("otf/KaTeX_Main-Regular.otf")',
    'Open("pfa/cmmi10.pfa")',
    'Select(0x2C)','Copy()',
    'Open("otf/KaTeX_Main-Regular.otf")',
    'Select(0u21AA)','Paste()',
    'Select(0u2192)','Copy()',
    'Select(0u21AA)',
    'PasteWithOffset(126,0)',
    'SetRBearing(848,1)',
    'RemoveOverlap()','Simplify()',
  ],
```
in `makeFF` to copy glyphs from other font files into the .otf files that `makeFF` produces.

**Comment by ylemkimon** [comment]
Tracked in https://github.com/KaTeX/KaTeX/issues/2886.
