### ISSUE TITLE
astronomical symbols using the wasysym package

### ISSUE THREAD

**Issue by kevinbarabash** [KaTeX/katex-fonts#21]
We should be able to use the `wasy` font.  See https://ctan.org/pkg/wasysym for details.  Also, https://mirror.hmc.edu/ctan/support/pkfix-helper/encoding-samples.pdf contains font layout information for the `wasy` font.

**Comment by kevinbarabash** [comment]
Tracking font changes in https://github.com/KaTeX/katex-fonts/issues/21.

**Comment by ylemkimon** [comment]
Tracked in https://github.com/KaTeX/KaTeX/issues/373.
