### ISSUE TITLE
small caps

### ISSUE THREAD

**Issue by kevinbarabash** [KaTeX/katex-fonts#28]
According to http://ctan.forsale.plus/fonts/amsfonts/doc/amsfndoc.pdf cmcsc10 is used for small caps.

**Comment by kevinbarabash** [comment]
<img width="863" alt="screen shot 2018-02-03 at 1 08 06 am" src="https://user-images.githubusercontent.com/1044413/35763652-c8caf556-087e-11e8-8dcc-397cc942bf37.png">

**Comment by ylemkimon** [comment]
Tracked in https://github.com/KaTeX/KaTeX/issues/471.
