### ISSUE TITLE
Generation of redundant bold glyphs?

### ISSUE THREAD

**Issue by ylemkimon** [KaTeX/katex-fonts#40]
During clean-up of font generation scripts, it was discovered that extra glyphs like `\cdots` and `\longleftarrow` for `Main-Bold` font were generated.

However, it seems that it's not used in the KaTeX, nor is it possible to access them.

Is it used anywhere? Or, will it be used in the future?

https://github.com/KaTeX/katex-fonts/blob/2b91a1cdd1c9f64c1333470d69dcb5362a215197/src/fonts/OTF/TeX/makeFF#L1899-L2169

CC @kevinbarabash @edemaine

**Comment by edemaine** [comment]
They ought to be possible to access via `\boldsymbol`

```latex
\begin{align*}
\cdots\boldsymbol\cdots
\end{align*}
```
renders on quicklatex as:
![image](https://user-images.githubusercontent.com/2218736/38439570-18aa0cd4-39ac-11e8-99f5-08ad248a2588.png)

So I think we should keep them, and add access to them.  (Their definition looks like a poor man's bold, though.  Are there really no symbols for them in AMS fonts or something?)

**Comment by ylemkimon** [comment]
@edemaine I thought it should be in `Main-BoldItalic`, but now I see symbols are in `Main`.
