### ISSUE TITLE
\notin missing metrics, \notin & \neq wrong glyph

### ISSUE THREAD

**Issue by edemaine** [KaTeX/katex-fonts#47]
As mentioned [here](https://github.com/Khan/KaTeX/pull/1385#discussion_r192178261), the `\notin` symbol (U+2209, 8713 in decimal) is missing font metrics.  This seems to be an isolated instance, but maybe worth checking for other missing characters.

Once this is fixed, we should change the corresponding KaTeX test to check `toBuild` instead of `toParse`.

**Comment by kevinbarabash** [comment]
I should probably check that `notin` still works after my changes to `0x338`.
```
  notin => [
    'Select(0u2208)','Copy()',
    'Select(0u2209)','Paste()',
    'Select(0u338)','Copy()',
    'Select(0u2209)',
#    'PasteWithOffset(-63,0)',
    'PasteWithOffset(831,0)',
    'RemoveOverlap()',
  ],
```

**Comment by edemaine** [comment]
Indeed, the glyph is now messed up:  (via https://opentype.js.org/glyph-inspector.html)

![image](https://user-images.githubusercontent.com/2218736/40853973-d5fc3a60-659d-11e8-83fb-391408320cb8.png)

The metrics for 8713 are still missing, too.  Perhaps we should remove this glyph altogether, and define a macro `\notin` -> `\not\in` (as in LaTeX)?

**Comment by kevinbarabash** [comment]
@edemaine thanks for checking those glyphs.  I'll work on this this weekend.

**Comment by edemaine** [comment]
Here is how `\neq` and `\notin` are defined in LaTeX (`base/fontmath.ltx`):

```latex
\def\neq{\not=} \let\ne=\neq
\DeclareRobustCommand
  \notin{\mathrel{\m@th\mathpalette\c@ncel\in}}
\def\c@ncel#1#2{\m@th\ooalign{$\hfil#1\mkern1mu/\hfil$\crcr$#1#2$}}
```

Based on this, I find the following macro definitions work well in KaTeX:

```js
defineMacro("\\neq", "\\not=");
defineMacro("\\notin", "\\not\\mskip1mu\\in");
```

But the latter one isn't *quite* perfect -- slightly off spacing before/after symbol.  So maybe easier to just fix the symbols after all.

**Comment by kevinbarabash** [comment]
Striving for the ability to use macros to define more things I think it is a good direction b/c modifying fonts takes considerably more time/effort.

**Comment by edemaine** [comment]
OK, I'm making a new PR for the macro approach.

**Comment by kevinbarabash** [comment]
I'm going to put this on hold until that gets merged.

**Comment by edemaine** [comment]
The master branch now features bad glyphs for `\neq` and `\notin`.  Luckily, they're no longer used by KaTeX.  But we should remove the glyphs.  I'll take a look.
