### ISSUE TITLE
Add italic capital Greek letters

### ISSUE THREAD

**Issue by edemaine** [KaTeX/katex-fonts#7]
AMS defines these macros for italic capital Greek letters:
```latex
\varGamma
\varDelta
\varTheta
\varLambda
\varXi
\varPi
\varSigma
\varUpsilon
\varPhi
\varPsi
\varOmega
```
These are the remaining characters (I believe) needed for https://github.com/Khan/KaTeX/issues/130

**Comment by ylemkimon** [comment]
This is no longer needed as https://github.com/Khan/KaTeX/pull/1118 was merged.
