### ISSUE TITLE
for which katex functions are these fonts used?

### ISSUE THREAD

**Issue by tessus** [KaTeX/katex-fonts#74]
We use Katex in Joplin, but run into rendering issues now and again. Most likely because we haven't added all fonts. Laurent is reluctant to add all fonts without knowing what they are actually used for.

Is there a list or matrix of why these fonts are used and what for?

I checked the contributing doc, but there's no reference to a help forum or something else.
So I hope it's ok to ask a question here.

**Comment by tessus** [comment]
Ah, I see. I can't handle all the replies and comments.

**Comment by kevinbarabash** [comment]
@tessus did you find the info you were looking for?

**Comment by tessus** [comment]
Nope, we've added all fonts instead. 

However, a matrix or info in the doc would still be nice as a reference. Should you ever add that info, please let m know in this issue so that I get a notification.

**Comment by kevinbarabash** [comment]
It's tough since there isn't a one-to-one mapping between commands and fonts.  Some things like delimiters will load different fonts based on the size of the group they wrap.

**Comment by kevinbarabash** [comment]
Does joplin limit which commands can be used when entering math?

**Comment by tessus** [comment]
No, it doesn't.

**Comment by kevinbarabash** [comment]
In that case including all of the fonts was the right call. 🙂
