### ISSUE TITLE
Add \S, \P

### ISSUE THREAD

**Issue by edemaine** [KaTeX/katex-fonts#9]
These symbols (copyright, section mark, paragraph mark) are in standard LaTeX in text and math modes; see Table 3 of http://tug.ctan.org/info/symbols/comprehensive/symbols-a4.pdf#page=15.  (We support all other symbols in Table 3.) We're missing them in the fonts.

Once we add them, https://github.com/Khan/KaTeX/pull/1061 adds KaTeX support for them.

**Comment by kevinbarabash** [comment]
According to https://mirror.hmc.edu/ctan/support/pkfix-helper/encoding-samples.pdf,`\S` is character 120 (dec) from cmsy and `\P` is character 123 (dec) from cmsy.  Looking at the output of `\copyright`:
```
..\hbox(4.60695+1.94444)x10.00002
...\hbox(4.60695+1.94444)x10.00002
....\vbox(4.60695+1.94444)x10.00002
.....\hbox(4.60695+0.0)x10.00002
......\glue(\tabskip) 0.0
......\hbox(4.60695+0.0)x10.00002, glue set 2.77779fil
.......\glue 0.0 plus 1.0fil
.......\hbox(4.30554+0.0)x4.44444, shifted -0.3014
........\OT1/cmr/m/n/10 c
.......\glue 0.0 plus 1.0fil
......\glue(\tabskip) 0.0
.....\glue(\baselineskip) -6.94444
.....\hbox(6.94444+1.94444)x10.00002
......\glue(\tabskip) 0.0
......\hbox(6.94444+1.94444)x10.00002
.......\OMS/cmsy/m/n/10 ^^M
......\glue(\tabskip) 0.0
```
it looks like LaTeX is combining `c` from cmr with an open circle from cmsy, specifically character 13 (dec).  `^^M = ^M = ASCII 13`

**Comment by kevinbarabash** [comment]
There are characters for `\copyright` in different fonts listed in the encoding-samples.pdf, but they all look a little different.  We might be able to simulate what LaTeX is doing for `\copyright` using `\clap` and `\raisebox`.

**Comment by edemaine** [comment]
Good sleuthing! Here is the LaTeX source for `\copyright`:

```latex
\DeclareTextAccentDefault{\textcircled}{OMS}
\DeclareTextCommandDefault{\textcopyright}{\textcircled{c}}
\DeclareTextCommandDefault{\textregistered}{\textcircled{%
     \check@mathfonts\fontsize\sf@size\z@\math@fontsfalse\selectfont R}}
```

So I guess we'd ideally have the circled accent, presumably as a noncombining character unlike LaTeX, and then we can define `\copyright` as a macro.

**Comment by kevinbarabash** [comment]
Currently our accents are zero width.  In this case though, I think we'd want to preserve the width of the circle.  Also, we already have the correct glyph for the circle.  It's being used for `\bigcirc`.

**Comment by edemaine** [comment]
Oh, perfect! Agreed, `\clap` seems ideal.

**Comment by kevinbarabash** [comment]
`\bigcirc \clap{c}` didn't do what I thought it would do.

<img width="141" alt="screen shot 2018-01-15 at 10 48 00 am" src="https://user-images.githubusercontent.com/1044413/34950595-924a78b8-f9e1-11e7-8a4e-8876d0a7843f.png">

**Comment by edemaine** [comment]
`\clap{$\bigcirc$}\clap{c}` works reasonably well, but it has the wrong bounding box (zero width, centered in middle).  This is actually a place where fill glue would help, or `\widthof`... Or we could add manual spacing.
